insert into public.activities (title, description, location_text, location_url, lat, lng, type, age_range, area, cost, vibes, why_its_worth_it, what_to_watch_out_for, tips, nearby_food, start_date, end_date, recurrence) values

(
  'Woodland Park Zoo',
  'One of the oldest zoos on the West Coast, featuring naturalistic habitats and a fantastic kids'' zone with a play area and petting zoo.',
  'Woodland Park Zoo, Seattle',
  'https://maps.google.com/?q=Woodland+Park+Zoo+Seattle',
  47.6685, -122.3508,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  '$$',
  '{"Burn Energy", "Outdoor / Nature"}',
  'The zoo is huge and genuinely interesting for kids of all ages. The play areas alone are worth the trip for toddlers, and the African savanna exhibit is a showstopper. Membership pays for itself in about 3 visits.',
  '{"Parking fills up fast on weekends — arrive before 10am or use street parking on N 50th", "The south entrance has a big hill that can be tough with strollers", "Some exhibits close early in winter — check the seasonal schedule", "Food inside is pricey — pack lunch and eat at the covered picnic area near the playground"}',
  'Get the annual membership if you plan to go more than twice. Also works at Point Defiance Zoo.',
  '[{"name": "Bongos", "description": "Cuban sandwiches right outside the west entrance"}, {"name": "Peaks Frozen Custard", "description": "Great frozen custard spot nearby on Phinney Ave"}, {"name": "Pack a picnic", "description": "Tables near the north meadow and the playground area"}]',
  null, null, null
),

(
  'Seattle Children''s Museum',
  'A hands-on museum in Seattle Center designed for kids 10 and under, with imaginative play areas, art studios, and rotating exhibits.',
  'Seattle Children''s Museum, Seattle Center',
  'https://maps.google.com/?q=Seattle+Childrens+Museum',
  47.6215, -122.3493,
  'activity',
  '{"Toddler", "3-5", "5+"}',
  'Seattle',
  '$',
  '{"Rainy Day", "Chill / Easy"}',
  'This is the ultimate rainy day destination for young kids. The pretend neighborhood (grocery store, bus, clinic) is magical for toddlers. The art studio always has a fun project going. Easy to spend 2-3 hours without screens.',
  '{"Gets extremely crowded on rainy weekends — go right at opening or on a weekday", "Not great for kids over 8 — they''ll be bored quickly", "The museum is inside the Armory building but can be tricky to find — enter from the Seattle Center courtyard", "No re-entry — once you leave, you''re done"}',
  'Combine it with a ride on the monorail or a walk around the International Fountain.',
  '[{"name": "Armory Food Court", "description": "Literally upstairs — tacos, pizza, Thai, and more"}, {"name": "MOD Pizza", "description": "Quick custom pizzas a short walk away in Lower Queen Anne"}, {"name": "Toulouse Petit", "description": "Fancy brunch nearby if grandparents are tagging along"}]',
  null, null, null
),

(
  'Golden Gardens Beach',
  'A sandy beach park in Ballard with tide pools, fire pits, a playground, and mountain views. One of Seattle''s best family beaches.',
  'Golden Gardens Park, Seattle',
  'https://maps.google.com/?q=Golden+Gardens+Park+Seattle',
  47.6918, -122.4026,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  'Free',
  '{"Outdoor / Nature", "Chill / Easy", "Burn Energy"}',
  'The rare Seattle beach that actually feels like a beach. The sandy shore is great for digging, the tide pools north of the beach have crabs and anemones, and the playground is solid. On clear days the Olympic Mountain views are spectacular. Bonfires allowed in the fire pits.',
  '{"Parking lot fills by noon on sunny days — no joke, get there early", "The road down to the beach is steep and winding — not great for car-sick kids", "Water is always cold — bring towels and a change of clothes", "Dogs are allowed on the upper trail but not the beach — watch for off-leash pups anyway", "Bring firewood if you want a bonfire — you can''t gather wood on-site"}',
  'Low tide is the best time for tide pools. Check the tide chart before you go.',
  '[{"name": "Red Mill Burgers", "description": "Legendary Seattle burgers about 10 minutes away"}, {"name": "Pack a cooler", "description": "There''s nothing walkable — bring food and drinks"}, {"name": "Señor Moose", "description": "Great Mexican breakfast in Ballard on the way home"}]',
  null, null, null
),

(
  'Discovery Park',
  'Seattle''s largest park with 534 acres of forests, meadows, sea cliffs, and a historic lighthouse. Multiple trails from easy to moderate.',
  'Discovery Park, Seattle',
  'https://maps.google.com/?q=Discovery+Park+Seattle',
  47.6573, -122.4057,
  'activity',
  '{"All Ages", "3-5", "5+", "8+"}',
  'Seattle',
  'Free',
  '{"Outdoor / Nature", "Burn Energy"}',
  'This park is a treasure. The Loop Trail is a perfect 2.8-mile family hike through forest and meadows. The lighthouse trail is shorter and ends at a beach. It feels like wilderness but is 15 minutes from downtown. Eagle sightings are common.',
  '{"The lighthouse trail has a steep section that''s muddy when wet — not stroller friendly", "Cell service is spotty in the park", "The parking lot at the south entrance fills quickly — try the north lot", "Trails are not well-marked — bring a map or download the park map ahead of time", "No food or water available — pack everything you need"}',
  'The visitor center has free maps and a small nature exhibit. Start there.',
  '[{"name": "Fisherman''s Terminal", "description": "Fresh seafood at Chinook''s nearby in Magnolia"}, {"name": "Red Mill Burgers", "description": "Worth the detour through Interbay"}, {"name": "Pack a lunch", "description": "Picnic tables at the south bluff have amazing views"}]',
  null, null, null
),

(
  'Pike Place Market (Family Edition)',
  'Iconic Seattle market with fishmongers, fruit stands, street performers, and the original Starbucks. A sensory adventure for kids.',
  'Pike Place Market, Seattle',
  'https://maps.google.com/?q=Pike+Place+Market+Seattle',
  47.6097, -122.3422,
  'activity',
  '{"All Ages", "3-5", "5+", "8+"}',
  'Seattle',
  '$',
  '{"Special / Treat", "Quick Outing"}',
  'Kids love watching the fish throwers, tasting free samples at the fruit stands, and exploring the lower levels like a maze. The giant piggy bank and the gum wall are kid magnets. It''s chaotic and alive and genuinely fun for families if you go at the right time.',
  '{"Go early (before 10am) to avoid crushing crowds — it gets overwhelming for little ones by noon", "Stroller navigation is difficult on the cobblestones and in narrow aisles", "The gum wall is fun to see but maybe don''t let toddlers touch it", "Parking is expensive — use the Pike Place Market garage and validate at a vendor", "Lower levels can be confusing — stick together"}',
  'Start at the pig statue (Rachel), watch the fish throw, grab a pastry, then wander. Keep it to 1-2 hours with young kids.',
  '[{"name": "Piroshky Piroshky", "description": "Famous Russian pastries — kids love the sweet ones"}, {"name": "Ellenos Greek Yogurt", "description": "Best yogurt you''ll ever have, right in the market"}, {"name": "Beecher''s Mac & Cheese", "description": "World-class mac and cheese that kids (and adults) devour"}]',
  null, null, null
),

(
  'Bellevue Downtown Park',
  'A 21-acre park in the heart of downtown Bellevue with a huge circular lawn, a 240-foot wide waterfall, and a fantastic new playground.',
  'Bellevue Downtown Park, Bellevue',
  'https://maps.google.com/?q=Bellevue+Downtown+Park',
  47.6101, -122.2015,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Eastside',
  'Free',
  '{"Chill / Easy", "Burn Energy", "Quick Outing"}',
  'The playground here was recently renovated and it''s incredible — multiple play structures for different ages, a water feature in summer, and rubber flooring everywhere. The canal walk is great for toddlers, and the big lawn is perfect for running around or flying kites. Very clean and well-maintained.',
  '{"Can get hot in summer — limited shade on the main lawn", "The playground is popular — weekend afternoons are packed", "Parking in the garage off Bellevue Way is the easiest option", "No food vendors in the park — bring snacks"}',
  'Combine with a walk through Bellevue Square if the weather turns.',
  '[{"name": "Din Tai Fung", "description": "World-famous dumplings at Bellevue Square, short walk away"}, {"name": "Homegrown", "description": "Great sandwiches and salads just across the street"}, {"name": "Fran''s Chocolates", "description": "Treat yourself to fancy Seattle chocolates nearby"}]',
  null, null, null
),

(
  'Ballard Locks (Hiram M. Chittenden Locks)',
  'Watch boats move between Puget Sound and Lake Union through the lock system. The fish ladder has underwater viewing windows during salmon season.',
  'Ballard Locks, Seattle',
  'https://maps.google.com/?q=Ballard+Locks+Seattle',
  47.6655, -122.3976,
  'activity',
  '{"All Ages", "3-5", "5+", "8+"}',
  'Seattle',
  'Free',
  '{"Chill / Easy", "Outdoor / Nature", "Quick Outing"}',
  'It''s mesmerizing to watch boats rise and fall as the locks fill and drain. The fish ladder viewing windows (June-September) let you watch salmon swimming upstream — kids are glued to them. The botanical gardens on-site are beautiful and free. A perfect 1-2 hour outing.',
  '{"Fish ladder is most active June through September — off-season it''s empty", "The visitor center closes early — check hours before going", "The path along the locks is narrow and not fully fenced — hold hands with little ones", "No food available inside — bring snacks or eat in Ballard first"}',
  'The visitor center has a great free video explaining how locks work. Watch it first — makes the experience way more interesting for kids.',
  '[{"name": "Red Star Taco Bar", "description": "Fun and casual tacos in Ballard, 5 min drive"}, {"name": "Bitterroot BBQ", "description": "Solid BBQ right in the Ballard restaurant strip"}, {"name": "Salt & Straw", "description": "Adventurous ice cream flavors on Ballard Ave"}]',
  null, null, null
),

(
  'Museum of Flight',
  'The largest air and space museum on the West Coast, with real planes, a space shuttle trainer, and hands-on flight simulators.',
  'Museum of Flight, Tukwila',
  'https://maps.google.com/?q=Museum+of+Flight+Seattle',
  47.5180, -122.2964,
  'activity',
  '{"3-5", "5+", "8+", "12+"}',
  'South',
  '$$',
  '{"Rainy Day", "Special / Treat"}',
  'This place is jaw-dropping for kids who are into planes, space, or just big machines. You can walk through a Concorde, sit in a real cockpit, and the space gallery has actual spacecraft. The kids'' flight zone has building activities and simple simulators. Plan for at least 3 hours.',
  '{"It''s far south — plan for 20-30 min drive from downtown Seattle", "The museum is enormous — little kids will tire out, so prioritize sections", "Flight simulators cost extra and have long waits on weekends", "Not much for toddlers — best for age 4+", "Parking is free but the lot is massive — remember where you parked"}',
  'First Thursday evenings are free admission. The outdoor aviation pavilion (free to access) has Air Force One and a Concorde.',
  '[{"name": "Pack lunch", "description": "The museum café is mediocre — eat before or after"}, {"name": "Katsu Burger", "description": "Japanese-style burgers nearby, very kid friendly"}, {"name": "Ivar''s Seafood", "description": "Classic Seattle fish and chips at the Renton location nearby"}]',
  null, null, null
),

(
  'Green Lake',
  'A 2.8-mile paved loop around a beautiful urban lake with playgrounds, a wading pool, paddle boats, and year-round activity.',
  'Green Lake Park, Seattle',
  'https://maps.google.com/?q=Green+Lake+Park+Seattle',
  47.6812, -122.3282,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  'Free',
  '{"Burn Energy", "Outdoor / Nature", "Chill / Easy"}',
  'Green Lake is where Seattle families go to just... be outside. The flat paved path is perfect for bikes, scooters, and strollers. Two playgrounds, a wading pool in summer, and paddle boats for rent. It''s never boring and always beautiful.',
  '{"The path gets congested on sunny weekends — bikes and pedestrians share space", "Wading pool is summer only and closes when it''s cloudy (yes, really)", "Geese are everywhere and can be aggressive — keep snacks sealed", "Parking around the lake is free but can take a while to find a spot"}',
  'Rent a pedal boat or kayak at the Green Lake Boat Rental dock (seasonal). The east side playground is newer and better than the west side.',
  '[{"name": "Greenlake Guest House Coffee", "description": "Cozy coffee spot right across from the lake"}, {"name": "Wayward Vegan Café", "description": "Excellent comfort food near the east side of the lake"}, {"name": "Spud Fish & Chips", "description": "Classic fish and chips with a counter right by the lake"}]',
  null, null, null
),

(
  'WA State Fair (Puyallup Fair)',
  'The largest single attraction in Washington state. Rides, farm animals, fair food, concerts, and everything you''d expect from a state fair.',
  'Washington State Fairgrounds, Puyallup',
  'https://maps.google.com/?q=Washington+State+Fair+Puyallup',
  47.1985, -122.2927,
  'event',
  '{"All Ages", "Toddler", "3-5", "5+", "8+"}',
  'South',
  '$$',
  '{"Special / Treat", "Burn Energy"}',
  'The Puyallup Fair is a full-day Seattle-area tradition. Fisher scone? Mandatory. Kids go nuts for the farm animals, the rides are legitimately fun, and the food options are absurd (in the best way). It only comes once a year and it''s worth the pilgrimage.',
  '{"It''s in Puyallup — budget 45+ minutes for the drive from Seattle", "Parking is chaotic and expensive — consider the free shuttle from nearby lots", "Rides require separate tickets/wristbands on top of admission — budget accordingly", "It gets HOT in September — bring sunscreen, hats, and water", "The fair is massive — have a plan or you''ll wander aimlessly for hours"}',
  'Go on a weekday if at all possible. Buy tickets online in advance for a discount. The kids'' ride area is separate and calmer.',
  '[{"name": "Fisher Scones", "description": "The iconic fair food — warm scones with butter and jam. Non-negotiable."}, {"name": "Elephant Ears", "description": "Giant fried dough with cinnamon sugar — peak fair energy"}, {"name": "Everything on a stick", "description": "Corn dogs, chocolate-dipped cheesecake, deep-fried everything"}]',
  '2026-08-28', '2026-09-21', 'annual'
),

(
  'Seattle Aquarium',
  'A waterfront aquarium with touch pools, an underwater dome, and marine life from the Pacific Northwest. Recently expanded with a new Ocean Pavilion.',
  'Seattle Aquarium, Pier 59',
  'https://maps.google.com/?q=Seattle+Aquarium',
  47.6076, -122.3432,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  '$$',
  '{"Rainy Day", "Special / Treat", "Quick Outing"}',
  'The new Ocean Pavilion is a game-changer — it added a massive open-ocean exhibit that makes this feel like a totally different aquarium. The touch pools are still the best part for little kids. The underwater dome where sharks swim overhead never gets old. Perfect rainy day outing.',
  '{"Admission is pricey — check for city library passes or discount days", "Weekends are packed, especially when it rains — weekday mornings are best", "The aquarium is smaller than you might expect — 1.5-2 hours is typical", "Stroller parking inside is limited", "The waterfront can be windy and cold — bring a layer even in summer"}',
  'The Seattle Public Library has discount aquarium passes you can check out. Combine with a walk along the waterfront.',
  '[{"name": "Ivar''s Acres of Clams", "description": "Classic waterfront seafood right next door"}, {"name": "Ye Olde Curiosity Shop", "description": "Weird and wonderful souvenir shop on the pier — kids love it"}, {"name": "Pike Place Chowder", "description": "Award-winning chowder a short walk uphill at Pike Place"}]',
  null, null, null
),

(
  'Kerry Park',
  'A small viewpoint park on Queen Anne Hill with the most iconic view of the Seattle skyline, Space Needle, and Mount Rainier.',
  'Kerry Park, Queen Anne, Seattle',
  'https://maps.google.com/?q=Kerry+Park+Seattle',
  47.6295, -122.3600,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  'Free',
  '{"Quick Outing", "Chill / Easy"}',
  'This is THE Seattle photo spot. The entire skyline, Space Needle, and (on clear days) Mount Rainier in one frame. It''s tiny — just a strip of grass and a railing — but the view is genuinely breathtaking. Kids love spotting the ferries and pointing out the Space Needle. Perfect 15-minute stop.',
  '{"Street parking only and it''s very limited — be prepared to circle", "The park is on a sidewalk with a steep drop — hold onto toddlers", "Sunset is gorgeous but crowded with photographers — go earlier with kids", "Not a destination on its own — combine with something else nearby"}',
  'Best on clear days when Rainier is visible. Great to combine with a trip to Seattle Center or a meal in Lower Queen Anne.',
  '[{"name": "Toulouse Petit", "description": "Excellent brunch/dinner spot at the bottom of Queen Anne hill"}, {"name": "Pagliacci Pizza", "description": "Great pizza on Queen Anne Ave, very kid-friendly"}, {"name": "Molly Moon''s", "description": "Seattle''s beloved ice cream shop on Queen Anne Ave"}]',
  null, null, null
);
