insert into public.activities (title, description, location_text, location_url, lat, lng, type, age_range, area, cost, vibes, why_its_worth_it, what_to_watch_out_for, tips, nearby_food, start_date, end_date, recurrence, image_url) values

(
  'Mt. Rainier National Park',
  'An iconic 14,411-foot volcano with wildflower meadows, easy family trails, waterfalls, and visitor centers. Paradise and Sunrise are the two main areas for families.',
  'Mount Rainier National Park, WA',
  'https://maps.google.com/?q=Mount+Rainier+National+Park',
  46.8523, -121.7603,
  'activity',
  '{"All Ages", "3-5", "5+", "8+"}',
  'South',
  '$',
  '{"Outdoor / Nature", "Special / Treat", "Burn Energy"}',
  'There is nothing like seeing Rainier up close. The Paradise area has easy paved trails through wildflower meadows with jaw-dropping views. Kids love the snow patches that last into July, the marmots that pop up trailside, and the waterfalls. This is a full-day trip but absolutely worth it — it feels like another world.',
  '{"It''s a 2-2.5 hour drive from Seattle — not a quick outing", "Paradise parking lot fills by 10am on summer weekends — go early or try a weekday", "Weather changes fast — bring layers even on sunny days, it''s much colder at elevation", "The park entrance fee is $30 per vehicle (or free with an America the Beautiful pass)", "Snow blocks most trails until late June or July — check NPS trail conditions before going"}',
  'The Nisqually Vista Trail (1.2 miles) at Paradise is the best family trail — paved, short, and stunning views. Pack lunch and eat at the picnic area near the Paradise Inn.',
  '[{"name": "Paradise Inn Dining Room", "description": "Historic lodge restaurant inside the park — book ahead"}, {"name": "Whittaker''s Café", "description": "Coffee and sandwiches in Ashford, right before the park entrance"}, {"name": "Pack a cooler", "description": "Best option — eat at one of the scenic picnic areas inside the park"}]',
  null, null, null,
  'https://images.unsplash.com/photo-1571495185065-ae06bd716a6a?w=800&q=80'
),

(
  'UW Cherry Blossoms',
  'Every spring, the University of Washington Quad explodes with pink cherry blossoms. A free, stunning, quintessentially Seattle experience.',
  'UW Quad, University of Washington, Seattle',
  'https://maps.google.com/?q=University+of+Washington+Quad+Seattle',
  47.6567, -122.3066,
  'event',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Seattle',
  'Free',
  '{"Chill / Easy", "Quick Outing", "Special / Treat", "Outdoor / Nature"}',
  'The UW Quad has 29 Yoshino cherry trees that are about 90 years old, and when they bloom it is breathtaking. The Gothic architecture of the surrounding buildings makes the pink canopy feel almost magical. Kids love running through the petals, and it''s a perfect photo opportunity. Peak bloom lasts only about 1-2 weeks so check the bloom tracker.',
  '{"Peak bloom is unpredictable — usually mid-March but can range from early March to early April", "The Quad gets extremely crowded during peak bloom, especially on sunny weekends", "Parking on campus is limited and expensive — consider transit or parking in the U-District and walking", "Bloom only lasts 1-2 weeks — follow @uwcherryblossom on Instagram for updates", "Don''t shake the trees or pull branches — it damages them"}',
  'Check washington.edu/cherryblossoms for the bloom status. Go early morning on a weekday for the best experience. Combine with a walk around Drumheller Fountain for more views.',
  '[{"name": "U:Don Fresh Japanese Noodle Station", "description": "Excellent udon right in the U-District"}, {"name": "Cafe on the Ave", "description": "Classic cheap and cheerful Thai food on University Way"}, {"name": "Molly Moon''s", "description": "Ice cream on the Ave — the perfect cherry blossom companion"}]',
  '2026-03-10', '2026-04-05', 'annual',
  'https://images.unsplash.com/photo-1558495177-3b9304e075e7?w=800&q=80'
),

(
  'Snoqualmie Falls',
  'A spectacular 268-foot waterfall just 30 minutes east of Seattle. Easy to access with a short walk to the observation deck — one of Washington''s most visited natural attractions.',
  'Snoqualmie Falls, Snoqualmie, WA',
  'https://maps.google.com/?q=Snoqualmie+Falls+Washington',
  47.5417, -121.8376,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'Eastside',
  'Free',
  '{"Outdoor / Nature", "Quick Outing", "Chill / Easy"}',
  'The falls are genuinely spectacular — a 268-foot plunge that you can feel in your chest from the observation deck. It''s one of the easiest "wow" nature experiences near Seattle. The upper viewpoint is stroller-accessible and just a minute walk from the parking lot. There''s also a half-mile trail down to the base for older kids. Spring is peak flow and incredibly dramatic.',
  '{"The upper parking lot fills up fast on weekends — there''s overflow parking but it adds a walk", "The trail to the base of the falls is steep and can be slippery — not stroller friendly", "The mist from the falls can soak you at the lower viewpoint — bring a rain layer", "Gift shop is overpriced — skip it", "No swimming allowed at the base"}',
  'Spring has the most dramatic water flow. Go on a weekday morning to avoid crowds. The Salish Lodge at the top is famous for brunch if you want to make it a special outing.',
  '[{"name": "Salish Lodge & Spa", "description": "Upscale brunch with a view right above the falls — pricey but a treat"}, {"name": "Snoqualmie Ice Cream", "description": "Small batch ice cream in the nearby town of Snoqualmie"}, {"name": "North Bend Bar & Grill", "description": "Casual burgers and fries in North Bend, 5 minutes away"}]',
  null, null, null,
  'https://images.unsplash.com/photo-1592031258533-131f4c468e6c?w=800&q=80'
),

(
  'Gene Coulon Memorial Beach Park',
  'A beautiful waterfront park on Lake Washington in Renton with a playground, wading beach, walking trails, picnic shelters, and a swimming area. Great for a relaxed family day.',
  'Gene Coulon Memorial Beach Park, Renton, WA',
  'https://maps.google.com/?q=Gene+Coulon+Memorial+Beach+Park+Renton',
  47.5025, -122.2003,
  'activity',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'South',
  'Free',
  '{"Chill / Easy", "Outdoor / Nature", "Burn Energy"}',
  'Gene Coulon is one of the best-kept secrets on Lake Washington. The playground is excellent (recently updated), the paved waterfront path is perfect for bikes and scooters, and the swimming beach has a gradual entry that''s great for little ones. The views across Lake Washington to Mercer Island and the Cascades are beautiful. It never feels as crowded as Seattle parks.',
  '{"Lifeguards are only on duty during summer months — watch kids closely near the water", "The parking lot fills on hot summer days — arrive before 11am", "Geese can be aggressive near the picnic areas — keep food sealed", "The park is in Renton, about 20 minutes south of downtown Seattle", "No alcohol allowed in the park"}',
  'The 1.5-mile paved loop trail is flat and stroller-friendly. Bring bikes or scooters for the kids. The covered picnic shelters can be reserved for parties.',
  '[{"name": "Ivar''s Seafood", "description": "Classic fish and chips right inside the park"}, {"name": "Pack a picnic", "description": "Plenty of picnic tables and covered shelters with lake views"}, {"name": "Blazing Onion", "description": "Great burgers in the nearby Landing shopping center"}]',
  null, null, null,
  null
),

(
  'Skagit Valley Tulip Fields',
  'Every April, the Skagit Valley north of Seattle erupts with millions of tulips in every color. Two main farms — Tulip Town and RoozenGaarde — offer walking paths through the fields.',
  'Skagit Valley, Mt Vernon, WA',
  'https://maps.google.com/?q=Skagit+Valley+Tulip+Festival+Mount+Vernon+WA',
  48.4201, -122.3340,
  'event',
  '{"All Ages", "Toddler", "3-5", "5+"}',
  'North',
  '$',
  '{"Outdoor / Nature", "Special / Treat", "Chill / Easy"}',
  'Walking through rows of tulips that stretch to the horizon is something every kid (and adult) should experience. The colors are almost unreal. Kids love running through the rows, and the mountain backdrop makes every photo stunning. Tulip Town has a covered pavilion and indoor displays for rainy days. It only happens for about 3-4 weeks each April.',
  '{"It''s about a 60-mile drive north of Seattle — budget 1-1.5 hours each way", "The tulip fields are MUDDY — bring rain boots or shoes you don''t mind getting dirty", "Peak bloom varies year to year — check tulipfestival.org for field status", "Weekends are extremely crowded and traffic getting in can be brutal — go on a weekday if possible", "Admission is per person at each farm ($15-20/adult, kids often free under 5)"}',
  'Go on a weekday morning for the best experience. RoozenGaarde has the biggest fields. Tulip Town has more variety and indoor displays. You can do both in one trip.',
  '[{"name": "Calico Cupboard", "description": "Beloved bakery and café in La Conner, 15 minutes from the fields"}, {"name": "Snow Goose Produce", "description": "Farm stand with fresh produce, pie, and ice cream near the fields"}, {"name": "Pack snacks", "description": "There''s usually food trucks at the farms but lines are long"}]',
  '2026-04-01', '2026-04-30', 'annual',
  'https://images.unsplash.com/photo-1762376785639-713deb39a3b3?w=800&q=80'
);
